services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: resume_dev
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: development
      NEXT_TELEMETRY_DISABLED: 1
      NEXT_PUBLIC_APP_URL: http://localhost:3000
      HOSTNAME: "0.0.0.0"
      PORT: "3000"
    volumes:
      - .:/app
      - /app/node_modules
      - /app/.next
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost:3000/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
