FROM node:18-alpine AS base
RUN apk add --no-cache libc6-compat curl

WORKDIR /app

COPY package.json package-lock.json* ./
RUN npm install

EXPOSE 3000

ENV PORT=3000
ENV HOSTNAME="0.0.0.0"

CMD ["npm", "run", "dev"]
